# 服务器端口
server:
  port: 9090

spring:
  # 设置开发环境
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blogsys?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: '000910'
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    banner-mode: console

# Mybatis配置
mybatis:
  type-aliases-package: icu.shishc.entity
  mapper-locations: classpath:mapper/*.xml

pagehelper:
  # 指定分页插件使用mysql方言
  helper-dialect: mysql
  # 合理化分页参数： 例如pageNum <= 0时会查询第一页，pageNum > pages时会查询最后一页
  reasonable: true
  # 支持通过Mapper接口参数来传递分页参数
  support-methods-arguments: true
#  params：为了支持startPage(Object params)方法，增加了该参数来配置参数映射，用于从对象中根据属性名取值，
#  可以配置 pageNum,pageSize,count,pageSizeZero,reasonable，不配置映射的用默认值，
#  默认值为
#  pageNum=pageNum;
#  pageSize=pageSize;
#  count=countSql;
#  reasonable=reasonable;
#  pageSizeZero=pageSizeZero。
  params: count=countSql





