spring:
  # 配置开发环境
  profiles:
    active: dev
  # 数据源配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blogsys?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: '000910'